# Generated by Django 4.1.3 on 2023-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloapp", "0002_alter_forms_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forms",
            name="text",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
